// THEMES DEFINITIONS

export const THEMES = {
    // Pulp: the "default" sheet, red stripe side bar, sandy colored main area with a map motif
    'Pulp' : {
        LeftBarBGColour: "#ffffff",
        LeftBarBGImage: "/modules/swade-spices/assets/img/squared-paper-texture.jpg",
        LeftBarLogo: "/modules/swade-spices/assets/img/SW_LOGO_FP_2018.png",
        LeftBarHealthTextColour: "#8C0809",
        LeftBarStatusTextColour: "#000000FF",
        LeftBarDerivedNameTextColour: "#191813",
        LeftBarDerivedValueTextColour: "#191813",
        LeftBarDerivedModifierTextColour: "#191813",
        TopBarColour: "#5b0b0d",
        TopBarBGImage: "",
        BodyBGColour: "#cac1b4",
        BodyBGImage: "",
        CheckboxColour: "#6B6D6E",
        CheckboxColourChecked: "#ffffff",
        CheckmarkColour: "#8C0809",
        CharnameTextColour: "#ffffff",
        CheckmarkColourFocus: "#cf1818",
        MainBodyTabBackgroundColour: "#000000",
        MainBodyTabTextColour: "#ffffff",
    },
    // Horror: the "dark mode" sheet. Purple sidebar, black main white text. Gothic details
    'Horror': {
        LeftBarBGColour: "#ffffff",
        LeftBarBGImage: "",
        LeftBarLogo: "/modules/swade-spices/assets/img/SW_LOGO_FP_2018.png",
        LeftBarHealthTextColour: "#000000",
        LeftBarStatusTextColour: "#000000FF",
        LeftBarDerivedNameTextColour: "#191813",
        LeftBarDerivedValueTextColour: "#191813",
        LeftBarDerivedModifierTextColour: "#191813",
        TopBarColour: "#ffffff",
        TopBarBGImage: "",
        BodyBGColour: "#ffffff",
        BodyBGImage: "",
        CheckboxColour: "#6B6D6E",
        CheckboxColourChecked: "#ffffff",
        CheckmarkColour: "#8C0809",
        CharnameTextColour: "#ffffff",
        CheckmarkColourFocus: "#cf1818",
        MainBodyTabBackgroundColour: "#000000",
        MainBodyTabTextColour: "#ffffff",
    },
    // Wooden: good for wild west or steampunk settings. Wood side bar, Green felt main with brass details
    'Wooden': {
        LeftBarBGColour: "#ff2222",
        LeftBarBGImage: "",
        LeftBarLogo: "/modules/swade-spices/assets/img/SW_LOGO_FP_2018.png",
        LeftBarHealthTextColour: "#000000",
        LeftBarStatusTextColour: "#000000FF",
        LeftBarDerivedNameTextColour: "#191813",
        LeftBarDerivedValueTextColour: "#191813",
        LeftBarDerivedModifierTextColour: "#191813",
        TopBarColour: "#ff3333",
        TopBarBGImage: "",
        BodyBGColour: "#ff4444",
        BodyBGImage: "",
        CheckboxColour: "#6B6D6E",
        CheckboxColourChecked: "#ffffff",
        CheckmarkColour: "#8C0809",
        CharnameTextColour: "#ffffff",
        CheckmarkColourFocus: "#cf1818",
        MainBodyTabBackgroundColour: "#000000",
        MainBodyTabTextColour: "#ffffff",
    }
}